local scale = 0.5

DB_MapPOI.CreatePOI("taxinode-thysta",
        "Thysta",
        HORDE_FLIGHT_MASTER,
        -12392.007812,
        27.727474,
        3.254488,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-gyll",
        "Gyll",
        ALLIANCE_FLIGHT_MASTER,
        -14477.9,
        464.101,
        36.4656,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-gringer",
        "Gringer",
        HORDE_FLIGHT_MASTER,
        -14448.6,
        506.129,
        26.3565,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-gryth-thurden",
        "Gryth Thurden",
        ALLIANCE_FLIGHT_MASTER,
        -4821.13,
        -1152.4,
        502.295,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-alexandra-constantine",
        "Alexandra Constantine",
        ALLIANCE_FLIGHT_MASTER,
        -11110.2,
        -3437.1,
        79.282,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-felicia-maline",
        "Felicia Maline",
        ALLIANCE_FLIGHT_MASTER,
        -10538.034180,
        -1257.815186,
        33.264488,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-borgus-stoutarm",
        "Borgus Stoutarm",
        ALLIANCE_FLIGHT_MASTER,
        -8370.250000,
        -2807.372803,
        200.793427,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-vahgruk",
        "Vahgruk",
        HORDE_FLIGHT_MASTER,
        -7555.515137,
        -2171.646240,
        157.187271,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-grisha",
        "Grisha",
        HORDE_FLIGHT_MASTER,
        -6559.26,
        -1100.23,
        310.353,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-lanie-reed",
        "Lanie Reed",
        ALLIANCE_FLIGHT_MASTER,
        -6559.06,
        -1169.38,
        309.809,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-ariena-stormfeather",
        "Ariena Stormfeather",
        ALLIANCE_FLIGHT_MASTER,
        -9435.21,
        -2234.88,
        69.1882,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-gorrik",
        "Gorrik",
        HORDE_FLIGHT_MASTER,
        -6632.22,
        -2178.42,
        244.227,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-darla-harris",
        "Darla Harris",
        ALLIANCE_FLIGHT_MASTER,
        -702.561,
        -520.365,
        25.4029,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-thorgrum-borrelson",
        "Thorgrum Borrelson",
        ALLIANCE_FLIGHT_MASTER,
        -5424.850098,
        -2929.8701,
        340.414276,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-baldruc",
        "Baldruc",
        ALLIANCE_FLIGHT_MASTER,
        -3828.88,
        -4517.51,
        10.7437,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-shardi",
        "Shardi",
        HORDE_FLIGHT_MASTER,
        -3091.069824,
        -2814.797607,
        34.615108,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-dyslix-silvergrub",
        "Dyslix Silvergrub",
        FLIGHT_MASTER,
        -4590.253418,
        -3243.288086,
        34.219948,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-shellei-brondir",
        "Shellei Brondir",
        ALLIANCE_FLIGHT_MASTER,
        -3843.180908,
        -773.073547,
        1.128729,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-urda",
        "Urda",
        HORDE_FLIGHT_MASTER,
        -872.348206,
        -3510.996582,
        71.942085,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-cedrik-prose",
        "Cedrik Prose",
        ALLIANCE_FLIGHT_MASTER,
        -1213.676270,
        -2594.130615,
        34.363369,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-devrak",
        "Devrak",
        HORDE_FLIGHT_MASTER,
        -573.745850,
        -2554.406006,
        92.270996,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-bragok",
        "Bragok",
        FLIGHT_MASTER,
        -970.352112,
        -3573.105469,
        32.361980,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-omusa-thunderhorn",
        "Omusa Thunderhorn",
        HORDE_FLIGHT_MASTER,
        -2220.417236,
        -2022.008789,
        91.884323,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-zarise",
        "Zarise",
        HORDE_FLIGHT_MASTER,
        2.67557,
        -857.919,
        58.889,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-karos-razok",
        "Karos Razok",
        HORDE_FLIGHT_MASTER,
        473.939,
        1533.95,
        131.96,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-nyse",
        "Nyse",
        HORDE_FLIGHT_MASTER,
        -5424.128906,
        -2347.380615,
        84.751282,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-bera-stonehammer",
        "Bera Stonehammer",
        ALLIANCE_FLIGHT_MASTER,
        -7333.058594,
        -3724.663330,
        8.877570,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-bulkrek-ragefist",
        "Bulkrek Ragefist",
        HORDE_FLIGHT_MASTER,
        -7045.24,
        -3779.4,
        10.3158,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-gryfe",
        "Gryfe",
        FLIGHT_MASTER,
        -6110.54,
        -1140.35,
        -186.866,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-tal",
        "Tal",
        HORDE_FLIGHT_MASTER,
        -1196.75,
        26.0777,
        177.033,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-baritanas-skyriver",
        "Baritanas Skyriver",
        ALLIANCE_FLIGHT_MASTER,
        201.092102,
        1238.383423,
        182.552277,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-thalon",
        "Thalon",
        HORDE_FLIGHT_MASTER,
        -1770.37,
        3262.19,
        5.10852,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-teloren",
        "Teloren",
        ALLIANCE_FLIGHT_MASTER,
        2649.543457,
        1395.381714,
        229.637787,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-breyk",
        "Breyk",
        HORDE_FLIGHT_MASTER,
        -10399,
        -3360,
        22,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-tharm",
        "Tharm",
        HORDE_FLIGHT_MASTER,
        968.077,
        1042.29,
        104.563,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-vhulgra",
        "Vhulgra",
        HORDE_FLIGHT_MASTER,
        2305.64,
        -2520.15,
        103.893,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-andruk",
        "Andruk",
        HORDE_FLIGHT_MASTER,
        3373.69,
        994.351,
        5.36158,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-suralais-farwind",
        "Suralais Farwind",
        ALLIANCE_FLIGHT_MASTER,
        3002.88,
        -3206.81,
        190.114,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-daelyshia",
        "Daelyshia",
        ALLIANCE_FLIGHT_MASTER,
        2828.38,
        -284.25,
        106.69,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-jarrodenus",
        "Jarrodenus",
        ALLIANCE_FLIGHT_MASTER,
        2684.325684,
        -3913.191406,
        111.928162,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-kroum",
        "Kroum",
        HORDE_FLIGHT_MASTER,
        3664.02,
        -4390.45,
        113.169,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-caylais-moonfeather",
        "Caylais Moonfeather",
        ALLIANCE_FLIGHT_MASTER,
        6343.2,
        561.651,
        16.1047,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-michael-garrett",
        "Michael Garrett",
        HORDE_FLIGHT_MASTER,
        1567.12,
        266.345,
        -43.0194,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-mishellena",
        "Mishellena",
        ALLIANCE_FLIGHT_MASTER,
        6204.08,
        -1951.43,
        571.581,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-brakkar",
        "Brakkar",
        HORDE_FLIGHT_MASTER,
        5064.72,
        -338.845,
        367.463,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-gorrim",
        "Gorrim",
        FLIGHT_MASTER,
        3895.765137,
        -1273.020386,
        221.013870,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-maethrya",
        "Maethrya",
        ALLIANCE_FLIGHT_MASTER,
        6800.5004882813,
        -4742.4404296875,
        701.49780273438,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-yugrek",
        "Yugrek",
        HORDE_FLIGHT_MASTER,
        6815.2451171875,
        -4610.2719726563,
        710.66912841797,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-sindrayl",
        "Sindrayl",
        ALLIANCE_FLIGHT_MASTER,
        7454.85,
        -2491.61,
        462.699,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-faustron",
        "Faustron",
        HORDE_FLIGHT_MASTER,
        7466.15,
        -2122.08,
        492.427,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-cloud-skydancer",
        "Cloud Skydancer",
        ALLIANCE_FLIGHT_MASTER,
        -6758.55,
        775.594,
        89.1046,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-runk-windtamer",
        "Runk Windtamer",
        HORDE_FLIGHT_MASTER,
        -6844.227051,
        884.716614,
        33.438248,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-nizzle",
        "Nizzle",
        ALLIANCE_FLIGHT_MASTER,
        -11385.729492,
        -260.157745,
        62.197693,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-bibilfaz-featherwhistle",
        "Bibilfaz Featherwhistle",
        ALLIANCE_FLIGHT_MASTER,
        928.273,
        -1429.08,
        64.8343,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-vesprystus",
        "Vesprystus",
        ALLIANCE_FLIGHT_MASTER,
        8640.58,
        841.118,
        23.3464,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-fyldren-moonfeather",
        "Fyldren Moonfeather",
        ALLIANCE_FLIGHT_MASTER,
        -4370.54,
        3340.11,
        12.352,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-shyn",
        "Shyn",
        HORDE_FLIGHT_MASTER,
        -4377.758301,
        136.844482,
        25.764082,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-thyssiana",
        "Thyssiana",
        ALLIANCE_FLIGHT_MASTER,
        -4469.984863,
        -696.327271,
        -18.766151,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-khaelyn-steelwing",
        "Khaelyn Steelwing",
        ALLIANCE_FLIGHT_MASTER,
        2231.198486,
        -5354.851562,
        84.530891,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-georgia",
        "Georgia",
        HORDE_FLIGHT_MASTER,
        2328.48,
        -5290.72,
        81.8744,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-skymistress-gloaming",
        "Skymistress Gloaming",
        HORDE_FLIGHT_MASTER,
        9376.08,
        -7165.45,
        9.04866,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-barley",
        "Barley",
        HORDE_FLIGHT_MASTER,
        233.137,
        2632.3,
        88.3007,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-flightmaster-krill-bitterhue",
        "Flightmaster Krill Bitterhue",
        ALLIANCE_FLIGHT_MASTER,
        -665.804,
        2715.48,
        94.1981,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-laando",
        "Laando",
        ALLIANCE_FLIGHT_MASTER,
        -1930.02,
        -11956.8,
        57.4743,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-stephanos",
        "Stephanos",
        ALLIANCE_FLIGHT_MASTER,
        -4057.15,
        -11788.6,
        8.87662,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-kuma",
        "Kuma",
        ALLIANCE_FLIGHT_MASTER,
        199.061,
        4238.42,
        121.81,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-munci",
        "Munci",
        ALLIANCE_FLIGHT_MASTER,
        210.492,
        6065.09,
        148.396,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-furgu",
        "Furgu",
        ALLIANCE_FLIGHT_MASTER,
        -2723.1,
        7302.84,
        88.7157,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-duga",
        "Du'ga",
        HORDE_FLIGHT_MASTER,
        223.468,
        7812.55,
        22.6859,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-kerna",
        "Kerna",
        HORDE_FLIGHT_MASTER,
        -2563.19,
        4426.77,
        39.4383,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-gursha",
        "Gursha",
        HORDE_FLIGHT_MASTER,
        -1256.63,
        7136.17,
        57.3484,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-furnan-skysoar",
        "Furnan Skysoar",
        ALLIANCE_FLIGHT_MASTER,
        -2995.4,
        3873.27,
        9.6248,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-vlagga-freyfeather",
        "Vlagga Freyfeather",
        HORDE_FLIGHT_MASTER,
        -176.42,
        1028.53,
        54.2562,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-amish-wildhammer",
        "Amish Wildhammer",
        ALLIANCE_FLIGHT_MASTER,
        -323.81,
        1027.61,
        54.2399,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-amerun-leafshade",
        "Amerun Leafshade",
        ALLIANCE_FLIGHT_MASTER,
        2187.88,
        6794,
        183.413,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-krexcil",
        "Krexcil",
        FLIGHT_MASTER,
        3085.3,
        3600.82,
        144.009,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-brubeck-stormfoot",
        "Brubeck Stormfoot",
        ALLIANCE_FLIGHT_MASTER,
        -4009.603271,
        2262.484131,
        114.358757,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-innalia",
        "Innalia",
        HORDE_FLIGHT_MASTER,
        -589.569824,
        4184.216797,
        64.108948,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-unoke-tenderhoof",
        "Unoke Tenderhoof",
        HORDE_FLIGHT_MASTER,
        2451.06,
        6022.06,
        154.839,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-drekgol",
        "Drek'Gol",
        HORDE_FLIGHT_MASTER,
        -3060.706787,
        2498.517822,
        64.056068,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-amilya-airheart",
        "Amilya Airheart",
        HORDE_FLIGHT_MASTER,
        -1314.93,
        2355.39,
        89.0385,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-maddix",
        "Maddix",
        FLIGHT_MASTER,
        -3062.63,
        741.933,
        -10.0639,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-grennik",
        "Grennik",
        FLIGHT_MASTER,
        4071.264160,
        2982.904053,
        352.323547,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-harpax",
        "Harpax",
        FLIGHT_MASTER,
        2973.2,
        1848.45,
        141.085,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-gurzil",
        "Gur'zil",
        HORDE_FLIGHT_MASTER,
        119.191742,
        5286.898438,
        21.511032,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-rip-pedalslam",
        "Rip Pedalslam",
        ALLIANCE_FLIGHT_MASTER,
        1860.71,
        5528.27,
        277.588,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-alieshor",
        "Alieshor",
        FLIGHT_MASTER,
        -4041.257080,
        1099.935425,
        37.371014,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-fhyn-leafshadow",
        "Fhyn Leafshadow",
        FLIGHT_MASTER,
        2947.901611,
        5425.326172,
        145.782333,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-skymaster-maxxor",
        "Sky-Master Maxxor",
        HORDE_FLIGHT_MASTER,
        2023.78,
        4702.71,
        150.667,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-halu",
        "Halu",
        ALLIANCE_FLIGHT_MASTER,
        1025.199829,
        7435.409668,
        27.331951,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-skymaster-sunwing",
        "Skymaster Sunwing",
        HORDE_FLIGHT_MASTER,
        7595.16,
        -6782.24,
        86.878,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-thor",
        "Thor",
        ALLIANCE_FLIGHT_MASTER,
        -10628.3,
        1037.27,
        34.1915,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-gorkas",
        "Gorkas",
        HORDE_FLIGHT_MASTER,
        -631.736,
        -4720.6,
        5.48226,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-guthrum-thunderfist",
        "Guthrum Thunderfist",
        ALLIANCE_FLIGHT_MASTER,
        282.096,
        -2001.28,
        194.127,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-kiz-coilspanner",
        "Kiz Coilspanner",
        FLIGHT_MASTER,
        6789.91,
        -7749.43,
        126.619,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-runetog-wildhammer",
        "Runetog Wildhammer",
        ALLIANCE_FLIGHT_MASTER,
        279.397,
        1489.76,
        -15.4411,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        530
)
DB_MapPOI.CreatePOI("taxinode-frax-bucketdrop",
        "Frax Bucketdrop",
        FLIGHT_MASTER,
        1943.14,
        -2561.74,
        60.9247,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-timothy-cunningham",
        "Timothy Cunningham",
        HORDE_FLIGHT_MASTER,
        1635.455811,
        -699.394714,
        50.656582,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-kurzel",
        "Kurzel",
        FLIGHT_MASTER,
        -9416.65,
        -1039,
        113.389,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        1383
)
DB_MapPOI.CreatePOI("taxinode-jock-lindsey",
        "Jock Lindsey",
        FLIGHT_MASTER,
        -8374.98,
        793.747,
        148.469,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        1383
)
DB_MapPOI.CreatePOI("taxinode-evax-oilspark",
        "Evax Oilspark",
        FLIGHT_MASTER,
        -10710.2,
        1060.98,
        24.2352,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        1383
)
DB_MapPOI.CreatePOI("taxinode-doras",
        "Doras",
        HORDE_FLIGHT_MASTER,
        1676.3341064453,
        -4313.4560546875,
        61.794807434082,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        1
)
DB_MapPOI.CreatePOI("taxinode-dungar-longdrink",
        "Dungar Longdrink",
        ALLIANCE_FLIGHT_MASTER,
        -8835.6142578125,
        489.29345703125,
        109.61328125,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)
DB_MapPOI.CreatePOI("taxinode-pricilla-winterwind",
        "Pricilla Winterwind",
        ALLIANCE_FLIGHT_MASTER,
        685.965271,
        -4967.974609,
        5.937782,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-greer-orehammer",
        "Greer Orehammer",
        ALLIANCE_FLIGHT_MASTER,
        1269.572266,
        -3323.916016,
        200.963562,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-celea-frozenmane",
        "Celea Frozenmane",
        HORDE_FLIGHT_MASTER,
        2712.167480,
        -4252.903809,
        305.077911,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-james-ormsby",
        "James Ormsby",
        ALLIANCE_FLIGHT_MASTER,
        2468.332031,
        -5030.087891,
        283.563629,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-tobias-sarkhoff",
        "Tobias Sarkhoff",
        HORDE_FLIGHT_MASTER,
        360.026978,
        -4687.567383,
        245.371338,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-surristrasz",
        "Surristrasz",
        FLIGHT_MASTER,
        3580.071045,
        5912.592773,
        138.141495,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-turida-coldwind",
        "Turida Coldwind",
        HORDE_FLIGHT_MASTER,
        2931.736328,
        6215.000000,
        191.792923,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-narzun-skybreaker",
        "Narzun Skybreaker",
        HORDE_FLIGHT_MASTER,
        3830.734863,
        1703.395630,
        122.083664,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-kara-thricestar",
        "Kara Thricestar",
        ALLIANCE_FLIGHT_MASTER,
        4100.632812,
        5353.865723,
        29.530731,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-lilleth-radescu",
        "Lilleth Radescu",
        HORDE_FLIGHT_MASTER,
        2136.989258,
        -2950.694580,
        149.871185,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-junter-weiss",
        "Junter Weiss",
        HORDE_FLIGHT_MASTER,
        3244.797119,
        -580.402954,
        155.988510,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-omu-spiritbreeze",
        "Omu Spiritbreeze",
        HORDE_FLIGHT_MASTER,
        3461.203857,
        3991.211914,
        28.204889,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-kimbiza",
        "Kimbiza",
        HORDE_FLIGHT_MASTER,
        4382.752930,
        5620.518066,
        53.906673,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-numo-spiritbreeze",
        "Numo Spiritbreeze",
        HORDE_FLIGHT_MASTER,
        4941.589844,
        1167.949951,
        239.320129,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-nethestrasz",
        "Nethestrasz",
        FLIGHT_MASTER,
        3691.744385,
        158.873764,
        39.382187,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-kragh",
        "Kragh",
        HORDE_FLIGHT_MASTER,
        3341.874023,
        -2215.633789,
        119.373405,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-makki-wintergale",
        "Makki Wintergale",
        HORDE_FLIGHT_MASTER,
        3872.349609,
        -4442.029297,
        208.473114,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-samuel-clearbook",
        "Samuel Clearbook",
        ALLIANCE_FLIGHT_MASTER,
        4596.478516,
        -4296.232910,
        182.035828,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-derek-rammel",
        "Derek Rammel",
        ALLIANCE_FLIGHT_MASTER,
        4602.458008,
        1404.093018,
        194.938889,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-rodney-wells",
        "Rodney Wells",
        ALLIANCE_FLIGHT_MASTER,
        3686.032715,
        -722.223389,
        212.563446,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-tomas-riverwell",
        "Tomas Riverwell",
        ALLIANCE_FLIGHT_MASTER,
        2131.804932,
        5248.761719,
        19.445791,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-vana-grey",
        "Vana Grey",
        ALLIANCE_FLIGHT_MASTER,
        3378.410889,
        -2772.291504,
        195.993286,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_alliance",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-palena-silvercloud",
        "Palena Silvercloud",
        ALLIANCE_FLIGHT_MASTER,
        3389.094971,
        1944.103882,
        82.968536,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-warmage-adami",
        "Warmage Adami",
        FLIGHT_MASTER,
        3680.470215,
        6547.269531,
        221.343796,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-bat-handler-adeline",
        "Bat Handler Adeline",
        HORDE_FLIGHT_MASTER,
        1963.247559,
        -6039.889648,
        13.556749,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-the-spirit-of-gnomeregan",
        "The Spirit of Gnomeregan",
        FLIGHT_MASTER,
        5592.244629,
        5829.514160,
        -67.991905,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-bilko-driftspark",
        "Bilko Driftspark",
        FLIGHT_MASTER,
        2881.458008,
        4040.334473,
        4.668840,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-cid-flounderfix",
        "Cid Flounderfix",
        FLIGHT_MASTER,
        2829.010254,
        897.370178,
        15.960995,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-kip-trawlskip",
        "Kip Trawlskip",
        FLIGHT_MASTER,
        706.364319,
        -2917.366211,
        9.870499,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-marvin-wobblesprocket",
        "Marvin Wobblesprocket",
        FLIGHT_MASTER,
        5512.904297,
        4707.997559,
        -175.847488,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-baneflight",
        "Baneflight",
        FLIGHT_MASTER,
        5210.723145,
        -1357.707031,
        238.798157,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-danica-saint",
        "Danica Saint",
        FLIGHT_MASTER,
        5162.804688,
        -2147.547852,
        240.840042,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-gurric",
        "Gurric",
        FLIGHT_MASTER,
        5564.891113,
        -2616.641113,
        292.418945,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-maaka",
        "Maaka",
        FLIGHT_MASTER,
        5775.441895,
        -3634.274414,
        387.383179,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-aludane-whitecloud",
        "Aludane Whitecloud",
        FLIGHT_MASTER,
        5812.031250,
        452.444946,
        658.755066,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-skizzle-slickslide",
        "Skizzle Slickslide",
        FLIGHT_MASTER,
        6205.975098,
        -1163.478271,
        416.292084,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-faldorf-bitterchill",
        "Faldorf Bitterchill",
        ALLIANCE_FLIGHT_MASTER,
        6667.837402,
        -152.160645,
        968.751404,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-kabarg-windtamer",
        "Kabarg Windtamer",
        HORDE_FLIGHT_MASTER,
        7814.657227,
        -593.622314,
        1112.306030,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-hyeyoung-parka",
        "Hyeyoung Parka",
        HORDE_FLIGHT_MASTER,
        7806.543457,
        -2942.866455,
        1256.595337,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-breck-rockbrow",
        "Breck Rockbrow",
        FLIGHT_MASTER,
        8456.690430,
        -323.034698,
        906.848389,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-shavalius-the-fancy",
        "Shavalius THE Fancy",
        FLIGHT_MASTER,
        8921.061523,
        -1205.976440,
        1025.500244,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-skymaster-baeric",
        "Skymaster Baeric",
        HORDE_FLIGHT_MASTER,
        5597.373535,
        -693.671082,
        206.627472,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-galendror-whitewing",
        "Galendror Whitewing",
        ALLIANCE_FLIGHT_MASTER,
        5032.910156,
        -521.242004,
        225.991943,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-morlia-doomwing",
        "Morlia Doomwing",
        FLIGHT_MASTER,
        8316.090820,
        2765.056641,
        655.092590,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-aedan-moran",
        "Aedan Moran",
        FLIGHT_MASTER,
        6112.183594,
        -29.436987,
        383.510773,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-rafae",
        "Rafae",
        FLIGHT_MASTER,
        6902.611816,
        -4111.608887,
        467.354675,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-arzo-safeflight",
        "Arzo Safeflight",
        ALLIANCE_FLIGHT_MASTER,
        5097.091797,
        2178.574707,
        365.611755,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-herzo-safeflight",
        "Herzo Safeflight",
        HORDE_FLIGHT_MASTER,
        5023.399902,
        3686.030029,
        363.036072,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.HordeOnly),
        "taxinode_horde",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-penumbrius",
        "Penumbrius",
        FLIGHT_MASTER,
        6404.814941,
        471.776581,
        511.282898,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-dreadwind",
        "Dreadwind",
        FLIGHT_MASTER,
        7417.644531,
        4212.970703,
        314.217407,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-halvdan",
        "Halvdan",
        FLIGHT_MASTER,
        7309.450195,
        -2612.989990,
        814.844604,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)
DB_MapPOI.CreatePOI("taxinode-helidan-lightwing",
        "Helidan Lightwing",
        FLIGHT_MASTER,
        8473.988281,
        887.478882,
        547.293152,
        Enum.POIType.FlightMaster,
        Enum.POIFlags.HideOnContinent,
        "taxinode_neutral",
        scale,
        nil,
        571
)

DB_MapPOI.CreatePOI("taxinode-Grisalda",
        "Gryphon Master Grisalda",
        ALLIANCE_FLIGHT_MASTER,
        -7038.405762,
        1126.451172,
        328.637573,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)

DB_MapPOI.CreatePOI("taxinode-Stonefeather",
        "Gryphon Master Stonefeather",
        ALLIANCE_FLIGHT_MASTER,
        -6477.078613,
        -268.249359,
        576.797058,
        Enum.POIType.FlightMaster,
        EnumUtil.CombineMasks(Enum.POIFlags.HideOnContinent, Enum.POIFlags.AllianceOnly),
        "taxinode_alliance",
        scale,
        nil,
        0
)
