"""3.3.5 enum name tables. Partial by design: unmapped ids render as
EFFECT_<n>/AURA_<n>/TARGET_<n> - the id is always authoritative, the label is sugar."""

DISPEL_NAMES = {
    0: "None", 1: "Magic", 2: "Curse", 3: "Disease", 4: "Poison", 5: "Stealth",
    6: "Invisibility", 7: "All", 8: "SpecialNPCOnly", 9: "Enrage", 10: "ZGTicket",
}

SCHOOL_MASK_NAMES = {
    0x01: "Physical", 0x02: "Holy", 0x04: "Fire", 0x08: "Nature",
    0x10: "Frost", 0x20: "Shadow", 0x40: "Arcane",
}

def school_names(mask):
    return [n for b, n in SCHOOL_MASK_NAMES.items() if mask & b]

POWER_TYPES = {
    -2: "Health", 0: "Mana", 1: "Rage", 2: "Focus", 3: "Energy",
    4: "Happiness", 5: "Rune", 6: "RunicPower",
}

DMG_CLASS_NAMES = {0: "None", 1: "Magic", 2: "Melee", 3: "Ranged"}
PREVENTION_NAMES = {0: "None", 1: "Silence", 2: "Pacify"}
INSTANCE_TYPES = {0: "World", 1: "Dungeon", 2: "Raid", 3: "Battleground", 4: "Arena"}
LFG_TYPES = {1: "Dungeon", 2: "Raid", 4: "Zone", 5: "Heroic", 6: "Random"}

EFFECT_NAMES = {
    0: "NONE", 1: "INSTAKILL", 2: "SCHOOL_DAMAGE", 3: "DUMMY", 5: "TELEPORT_UNITS",
    6: "APPLY_AURA", 7: "ENVIRONMENTAL_DAMAGE", 8: "POWER_DRAIN", 9: "HEALTH_LEECH",
    10: "HEAL", 16: "QUEST_COMPLETE", 17: "WEAPON_DAMAGE_NOSCHOOL", 18: "RESURRECT",
    19: "ADD_EXTRA_ATTACKS", 24: "CREATE_ITEM", 27: "PERSISTENT_AREA_AURA",
    28: "SUMMON", 29: "LEAP", 30: "ENERGIZE", 31: "WEAPON_PERCENT_DAMAGE",
    32: "TRIGGER_MISSILE", 33: "OPEN_LOCK", 35: "APPLY_AREA_AURA_PARTY",
    36: "LEARN_SPELL", 38: "DISPEL", 40: "DUAL_WIELD", 44: "SKILL_STEP",
    48: "STEALTH", 53: "ENCHANT_ITEM", 54: "ENCHANT_ITEM_TEMPORARY",
    56: "SUMMON_PET", 58: "WEAPON_DAMAGE", 62: "POWER_BURN", 63: "THREAT",
    64: "TRIGGER_SPELL", 65: "APPLY_AREA_AURA_RAID", 67: "HEAL_MAX_HEALTH",
    68: "INTERRUPT_CAST", 75: "HEAL_MECHANICAL", 77: "SCRIPT_EFFECT",
    80: "ADD_COMBO_POINTS", 91: "THREAT_ALL", 96: "CHARGE", 98: "KNOCK_BACK",
    101: "FEED_PET", 102: "DISMISS_PET", 110: "DISPEL_MECHANIC",
    113: "RESURRECT_NEW", 121: "NORMALIZED_WEAPON_DMG",
    126: "STEAL_BENEFICIAL_BUFF", 135: "CALL_PET", 136: "HEAL_PCT",
    137: "ENERGIZE_PCT", 138: "LEAP_BACK", 142: "FORCE_CAST",
    151: "TRIGGER_SPELL_2",
}

AURA_NAMES = {
    0: "NONE", 3: "PERIODIC_DAMAGE", 4: "DUMMY", 5: "MOD_CONFUSE", 6: "MOD_CHARM",
    7: "MOD_FEAR", 8: "PERIODIC_HEAL", 9: "MOD_ATTACKSPEED", 10: "MOD_THREAT",
    11: "MOD_TAUNT", 12: "MOD_STUN", 13: "MOD_DAMAGE_DONE", 14: "MOD_DAMAGE_TAKEN",
    15: "DAMAGE_SHIELD", 16: "MOD_STEALTH", 18: "MOD_INVISIBILITY",
    20: "OBS_MOD_HEALTH", 21: "OBS_MOD_POWER", 22: "MOD_RESISTANCE",
    23: "PERIODIC_TRIGGER_SPELL", 24: "PERIODIC_ENERGIZE", 25: "MOD_PACIFY",
    26: "MOD_ROOT", 27: "MOD_SILENCE", 28: "REFLECT_SPELLS", 29: "MOD_STAT",
    30: "MOD_SKILL", 31: "MOD_INCREASE_SPEED", 33: "MOD_DECREASE_SPEED",
    34: "MOD_INCREASE_HEALTH", 35: "MOD_INCREASE_ENERGY", 36: "MOD_SHAPESHIFT",
    37: "EFFECT_IMMUNITY", 38: "STATE_IMMUNITY", 39: "SCHOOL_IMMUNITY",
    40: "DAMAGE_IMMUNITY", 41: "DISPEL_IMMUNITY", 42: "PROC_TRIGGER_SPELL",
    43: "PROC_TRIGGER_DAMAGE", 47: "MOD_PARRY_PERCENT", 49: "MOD_DODGE_PERCENT",
    51: "MOD_BLOCK_PERCENT", 52: "MOD_CRIT_PERCENT", 53: "PERIODIC_LEECH",
    54: "MOD_HIT_CHANCE", 55: "MOD_SPELL_HIT_CHANCE", 56: "TRANSFORM",
    57: "MOD_SPELL_CRIT_CHANCE", 60: "MOD_PACIFY_SILENCE", 61: "MOD_SCALE",
    64: "PERIODIC_MANA_LEECH", 65: "MOD_CASTING_SPEED_NOT_STACK",
    66: "FEIGN_DEATH", 67: "MOD_DISARM", 69: "SCHOOL_ABSORB",
    72: "MOD_POWER_COST_SCHOOL_PCT", 73: "MOD_POWER_COST_SCHOOL",
    74: "REFLECT_SPELLS_SCHOOL", 77: "MECHANIC_IMMUNITY", 78: "MOUNTED",
    79: "MOD_DAMAGE_PERCENT_DONE", 80: "MOD_PERCENT_STAT", 81: "SPLIT_DAMAGE_PCT",
    82: "WATER_BREATHING", 84: "MOD_REGEN", 85: "MOD_POWER_REGEN",
    87: "MOD_DAMAGE_PERCENT_TAKEN", 89: "PERIODIC_DAMAGE_PERCENT",
    94: "INTERRUPT_REGEN", 95: "GHOST", 97: "MANA_SHIELD",
    99: "MOD_ATTACK_POWER", 101: "MOD_RESISTANCE_PCT", 103: "MOD_TOTAL_THREAT",
    104: "WATER_WALK", 105: "FEATHER_FALL", 106: "HOVER",
    107: "ADD_FLAT_MODIFIER", 108: "ADD_PCT_MODIFIER", 109: "ADD_TARGET_TRIGGER",
    110: "MOD_POWER_REGEN_PERCENT", 123: "MOD_TARGET_RESISTANCE",
    124: "MOD_RANGED_ATTACK_POWER", 132: "MOD_INCREASE_ENERGY_PERCENT",
    133: "MOD_INCREASE_HEALTH_PERCENT", 134: "MOD_MANA_REGEN_INTERRUPT",
    135: "MOD_HEALING_DONE", 136: "MOD_HEALING_DONE_PERCENT",
    137: "MOD_TOTAL_STAT_PERCENTAGE", 138: "MOD_MELEE_HASTE",
    140: "MOD_RANGED_HASTE", 142: "MOD_BASE_RESISTANCE_PCT",
    143: "MOD_RESISTANCE_EXCLUSIVE", 144: "SAFE_FALL", 154: "MOD_STEALTH_LEVEL",
    189: "MOD_RATING", 200: "MOD_KILL_XP_PCT", 226: "PERIODIC_DUMMY",
    228: "DETECT_STEALTH", 231: "PROC_TRIGGER_SPELL_WITH_VALUE",
}

TARGET_NAMES = {
    0: "NONE", 1: "UNIT_CASTER", 5: "UNIT_PET", 6: "UNIT_TARGET_ENEMY",
    15: "DEST_AREA_ENEMY_SRC", 16: "DEST_AREA_ENEMY_DST", 18: "DEST_DEST",
    21: "UNIT_TARGET_ALLY", 22: "SRC_CASTER", 25: "UNIT_TARGET_ANY",
    30: "UNIT_AREA_ALLY_SRC", 31: "UNIT_AREA_ALLY_DST", 45: "UNIT_CHAINHEAL_ALLY",
    53: "DEST_TARGET_ENEMY", 57: "UNIT_TARGET_RAID", 61: "UNIT_AREA_CLASS_RAID",
}


def effect_name(n):
    return EFFECT_NAMES.get(n, f"EFFECT_{n}")


def aura_name(n):
    return AURA_NAMES.get(n, f"AURA_{n}")


def target_name(n):
    return TARGET_NAMES.get(n, f"TARGET_{n}")
