"""One entry point for the non-DBC raw layers: content, interface, cache.

    python -m tools.extract_raw_layers            # all three, then raw/README.md
    python -m tools.extract_raw_layers --only cache

Plain script, no agent, no manual step, deterministic: rerunning it on an
unchanged client rewrites byte-identical output. It reads the client and the
committed inventory; it never reads the curated `data/` tree, so it cannot
inherit a curation decision from it.

ORDER AND DEPENDENCIES
----------------------
`interface` is derived from `raw/_inventory/files/` and cross-checks every
sha256 it re-reads against it, so `python -m tools.inventory` must have run at
least once (it is committed, so normally it has). `content` and `cache` read the
client directly and depend on nothing else. The stages do not depend on each
other and can be run in any order or alone.

The DBC layer is NOT run from here - it has its own entry points
(`tools.extract_all` + `tools.decode_all`) and takes far longer. The final
`raw/README.md` this writes indexes every raw layer present, including those.
"""
import argparse
import json
import time
from pathlib import Path

from tools import (config, extract_cache, extract_content,
                   extract_interface_all, layerstate)
from tools.decode_all import write_text

STAGES = {
    "content": (extract_content.extract_all,
                "Data\\Content JSON + the .loc localization store"),
    "interface": (extract_interface_all.extract_all,
                  "every path under Interface\\ in the MPQ chain"),
    "cache": (extract_cache.extract_all,
              "Cache\\WDB query caches, base and per realm"),
}

# Every raw layer this repo can hold, with the file an agent should open first.
# Layers absent from disk are simply not listed in the generated README - the
# catalog describes what IS there, never what was expected to be there.
LAYERS = [
    ("_inventory", "README.md", "complete census of every file in the client"),
    ("tables", "index.json", "every DBC table, decoded, positional f0..fN"),
    ("dbc", None, "raw DBC bodies as extracted from the MPQ chain"),
    ("content", "index.json", "loose Data\\Content: JSON payloads + .loc localization"),
    ("interface", "_manifest.json", "Interface code layer (.lua/.xml/.toc) as bytes"),
    ("interface_all", "index.json", "every Interface path: size, sha256, text/binary"),
    ("cache", "index.json", "Cache\\WDB server query caches, per realm"),
    ("binaries", "index.json", "the client's own executables: strings, embedded "
                               "Lua, PE structure"),
    ("recovered", "README.md", "what was still opaque: deleted/encrypted "
                               "members, the files the old reader could not "
                               "read, CRC32+MD5+mtime per path, expanded "
                               "containers"),
    ("realms", None, "realm-overlay diff artifacts"),
    ("talents", None, "frozen capture of the external CoA talent builder"),
]

# Layers whose extractor writes a completion sentinel. The others predate it and
# are not regenerated by this pipeline, so "no sentinel" there is not a finding.
_SENTINEL_LAYERS = {"_inventory", "tables", "content", "interface",
                    "interface_all", "cache", "_catalog", "binaries",
                    "recovered"}


def _headline(d: Path, index_name) -> str:
    """A one-line size/count summary read OUT of the layer's own index, never
    hardcoded here - so this catalog cannot drift from the layers it indexes."""
    files = sum(1 for p in d.rglob("*") if p.is_file())
    size = sum(p.stat().st_size for p in d.rglob("*") if p.is_file())
    bits = [f"{files:,} files", f"{size/1e6:,.1f} MB"]
    if index_name and (d / index_name).is_file() and index_name.endswith(".json"):
        try:
            ix = json.loads((d / index_name).read_text(encoding="utf-8"))
        except Exception:
            return " / ".join(bits)
        for k in ("pathCount", "fileCount", "recordTotal", "locRecordTotal",
                  "count", "rows"):
            if isinstance(ix.get(k), int):
                bits.append(f"{k} {ix[k]:,}")
    return " / ".join(bits)


def _stage_block() -> tuple:
    """The regeneration commands, READ OUT of tools/extract_everything's stage
    table rather than restated here. The two used to be maintained separately
    and drifted the moment a stage was added - this README claimed six stages
    while the runner had seven, which is the exact failure the one-command entry
    point exists to prevent. Imported inside the function because
    extract_everything imports this module."""
    from tools import extract_everything as ee
    n = len(ee.STAGES)
    width = max(len(s[4]) for s in ee.STAGES)
    lines = [f"python -m {mod:<{width}}  # {i} {what}"
             for i, (_name, _fn, _dirs, what, mod) in enumerate(ee.STAGES, 1)]
    return n, "\n".join(lines)


def _census_facts() -> dict:
    """The completeness boundary's numbers, read from the census rather than
    typed into the prose. Every one of these drifts with a client patch, and a
    hardcoded 486,527 that the census had already moved past is exactly the kind
    of quietly-stale claim this file exists to avoid making."""
    ix = json.loads((config.RAW_DIR / "_inventory" / "files.json")
                    .read_bytes().decode("utf-8"))
    cats = json.loads((config.RAW_DIR / "_inventory" / "categories.json")
                      .read_bytes().decode("utf-8"))
    by_class = cats.get("byClass") or {}

    def cls(name, key):
        rec = by_class.get(name) or {}
        return rec.get(key) or 0

    return {
        "artFiles": cls("art", "files"), "artGB": cls("art", "bytes") / 1e9,
        "soundFiles": cls("sound", "files"),
        "soundGB": cls("sound", "bytes") / 1e9,
        "records": ix.get("recordCount") or 0,
        "unreadable": ix.get("unreadableCount") or 0,
    }


def write_root_readme() -> str:
    stage_count, stage_lines = _stage_block()
    facts = _census_facts()
    rows = []
    for name, index_name, what in LAYERS:
        d = config.RAW_DIR / name
        if not d.is_dir():
            continue
        entry = f"`raw/{name}/{index_name}`" if index_name else f"`raw/{name}/`"
        st = ("complete" if layerstate.is_complete(d)
              else "no sentinel" if name in _SENTINEL_LAYERS else "-")
        rows.append(f"| `{name}` | {what} | {entry} | {_headline(d, index_name)} "
                    f"| {st} |")
    text = f"""# raw/ - the client, mechanically extracted (generated)

Everything under `raw/` is written by a script in `tools/` from the client at
`{config.CLIENT_DIR}`. Nothing in it is hand-authored, hand-labelled or
hand-selected: column names are positional, types are inferred by measurement,
and no wanted-list decides what is extracted. Rerunning the scripts on an
unchanged client reproduces it byte for byte.

## Start here

| layer | what it holds | open first | size | state |
| --- | --- | --- | --- | --- |
{chr(10).join(rows)}

## Regenerating

One command rebuilds everything, in dependency order, and prints what changed
since the last run:

```
python -m tools.extract_everything                    # all {stage_count} stages (hours; reads the whole client)
python -m tools.extract_everything --list             # the stage list + each layer's current state
python -m tools.extract_everything --from decode_all  # resume at a stage
python -m tools.extract_everything --only build_catalog   # rerun exactly one stage
```

It is a thin runner over the {stage_count} stages, which stay individually runnable. Run
them in THIS order if you run them by hand - the order is the contract, because
three of them consume another's output:

```
{stage_lines}
```

Each stage writes its own `index.json`/`README.md` describing its own rules. No
stage requires an LLM, an argument or a decision.

## Half-written layers cannot happen silently

{layerstate.RULE}

The `state` column above is that sentinel. A layer marked `no sentinel` is not
to be read: it is either mid-run or was left behind by a crash.

## What "complete" means here, exactly

Stated as a boundary rather than left as an implication:

1. **Everything that can be extracted HAS been. Two exclusions, both by the
   repository owner's decision, both recorded rather than dropped:**

   - **Art and sound bytes are recorded, not committed.** Path, size and sha256
     are in this repo for every file in the client, but the bytes of {facts['artFiles']:,} art
     files ({facts['artGB']:.1f} GB) and {facts['soundFiles']:,} sound files ({facts['soundGB']:.1f} GB), plus the binary
     part of the Interface tree, stay in the client. That is a repository-size
     decision, applied mechanically by measurement (see
     `raw/interface_all/index.json` -> `sizeRule`), never a judgement about which
     files matter: every excluded byte is recoverable from the client and
     verifiable against the sha256 here.
   - **Install-specific data is excluded.** `WTF/`, `Logs/`, `Errors/`,
     `Screenshots/`, launcher logs and the user's own `Interface/AddOns` are
     machine state, not client content. They are also volatile between launches,
     so recording them would stop a rerun on an unchanged client from
     reproducing.

   Everything else in the client is extracted: 368 tables to positional columns,
   the whole Interface code layer, `Data/Content` and its `.loc` files, the WDB
   caches, every PE image's strings/Lua/structure, every non-winning VERSION of
   every table, and the deleted, encrypted and container members recovered in
   `raw/recovered/`.
2. **Complete for the installed product revision.** Which realm-scoped data a
   client carries is a property of the product, not of who is playing: the
   launcher's patcher ships exactly one realm overlay at a time, currently
   `Data/area-52` (Free-Pick's). No Conquest of Azeroth realm has a client data
   directory in this revision and no login creates one, so CoA reads the base
   chain and the base chain is what this repo is built on. `Cache/WDB/` is a
   different thing - a server-response cache written by playing - and the
   capture here covers CoA. NOTE that Rexxar and Vol'jin are two realms of the
   SAME game mode (Conquest of Azeroth, `gameMode=11`), so a cache captured on
   either one is a CoA capture and the other is not a missing half.

   `raw/cache` is the ONE layer whose source is not static client files, so it
   is also the one that reproduces byte for byte only against the same
   `Cache\\WDB` tree: playing the game appends to that cache, and the next run
   of this stage will legitimately differ. Everywhere else, "unchanged client"
   means "unchanged archives"; here it means "unchanged cache too".
3. **Every file in the client decodes, and the census now says so itself.**
   `raw/_inventory` used to record 41,051 of its {facts['records']:,} paths (6.4%) as
   `readable: false`. That was never a compression problem - it was `mpyq`,
   which is not a complete MPQ reader. `tools/inventory.py` has been moved onto
   `tools/mpq.py`, which is, and the census re-run: **{facts['unreadable']:,} paths remain
   `readable: false` and every one of them is an MPQ delete tombstone**, a patch
   entry that removes a path at its layer and carries no bytes by design. 0
   files are genuinely unreadable.

   The same move fixed the reverse problem. 1,271 members are stored with no
   sector offset table and `mpyq` mis-read 1,266 of them, so 1,186 sha256s in
   the old census were hashes of bytes that were never in the archive (music,
   cinematics, one nested archive - no data file among them, which is why the
   derived layers were never affected). The census now carries the true hashes.

   `raw/recovered/corrections/` and `raw/recovered/files/` are consequently
   **empty, and that is the result**: there is nothing left for them to correct
   or recover, because the census reads the client correctly itself. A non-empty
   `corrections/` means the census has drifted from the client again; the fix is
   `python -m tools.inventory`.

   All of this is verified against an oracle that is not another reader: every
   archive records an MD5 per member in its `(attributes)` block, and
   `python -m tools.crack --only verify` checks all **763,928** of them.
   Mismatches: 0. Census hashes it disagrees with: 0.
4. **The client's own executables are opened too.** `raw/binaries/` holds every
   printable string, the inlined Lua and the full PE structure of every PE image
   in the client - the seven loose in the client root, and the twenty stored
   INSIDE the MPQ archives under `_archived/` (`Wow.exe`, `Launcher.exe`,
   `Battle.net.dll`, `Repair.exe` and the rest, found by reading the bytes of
   every member the archives name). This is the layer that explains where
   `listarchive`, `SetDataPath` and the realm hot-swap script actually live,
   none of which is in any shipped data file.
5. **`Interface\\AddOns` on disk is out of scope** - it is the user's installed
   third-party addons, not client data. It is counted, never extracted, in
   `raw/interface_all/index.json` -> `onDiskInterfaceTree`. The one exception is
   `AddOns/APIDocumentation`, which is Ascension's own launcher-managed
   description of their API.
6. **What `raw/recovered/` still holds, now that the census reads the client
   itself.** `deleted/` is 4,911 patch tombstones recovered from the block
   tables - paths a patch layer REMOVES, which is real archive semantics and
   worth knowing. `empty/` is the 13 genuinely zero-length members.
   `attributes/` is the per-member CRC32 + MD5 + mtime each archive records
   about itself, which is the oracle everything else here is checked against.
   `containers/` is the nested archives, expanded. `files/` and `corrections/`
   are empty by construction - see boundary 3.

## The two rules that matter most when reading any of this

1. **A table has several VERSIONS, and the default pick is not always the one
   your question wants.** `Data\\<realm>\\` sits above every base and locale
   archive, so for 10 tables - `Spell.dbc` among them - the chain winner in
   `raw/tables/<Table>/` is the **area-52 overlay**, which is *Free-Pick's*
   data, carrying about 14% more spells than base. That is the right answer for
   a Free-Pick question and the WRONG one for a Conquest of Azeroth question:
   CoA realms have no client data directory at all and read the base chain.

   Nothing is thrown away - every distinct version of every table is decoded to
   `raw/tables/<Table>/variants/<archive-slug>/`, in the same shape and under
   the same rules as the winner, listed under `variants` in that table's
   `index.json` and all together in `raw/tables/_variants.json`. How to pick:

   ```
   python -m tools.find "Tide Lash"                      # the chain winner (may be the overlay)
   python -m tools.find "Tide Lash" --variant baseChain  # what a CoA character reads
   python -m tools.find "Tide Lash" --variant overlay    # the realm overlay only
   python -m tools.find "Tide Lash" --variant all        # every version, each labelled
   ```

   Every hit says which version it came from, so an answer can always name its
   layer. A LOOSE file at the client root outranks even the overlay: the client
   reads `<root>\\<path>` before it opens any archive, so
   `raw/_inventory/files.json` -> `looseOverrides` lists the paths whose winning
   bytes are on disk rather than in an MPQ.
2. **Columns are positional and types are measured.** `f5` means column 5. A
   type is what the bytes support, recorded with the counts behind it, not what
   a name suggests. Where a field layout IS named (the WDB caches), it was
   applied only because it consumed every record exactly, and even there the
   NAMES stay out of the data - they live in
   `raw/cache/_interpretation.json`, labelled as the unverified interpretation
   they are, because a permutation of same-width fields consumes the same bytes
   and so no name can be checked against the client.

## Searching it

```
python -m tools.find "Tide Lash"        # a string, across tables + .loc + WDB caches + binaries
python -m tools.find --id 133           # every column an integer appears in
python -m tools.find --joins-to Spell   # every column that points at Spell.f0
python -m tools.find "listarchive" --layer binaries   # the client's executables only
```
"""
    write_text(config.RAW_DIR / "README.md", text)
    return text


def main_stages(names=None, quiet: bool = False) -> dict:
    """Run the named stages (all of them by default) and rewrite raw/README.md.
    Split out of main() so tools/extract_everything.py can call it without argv."""
    out = {}
    for name in names or list(STAGES):
        fn, what = STAGES[name]
        t = time.time()
        print(f"== {name}: {what}", flush=True)
        out[name] = fn(verbose=not quiet)
        print(f"== {name}: done in {time.time() - t:.1f}s", flush=True)
    write_root_readme()
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--only", choices=sorted(STAGES), action="append",
                    help="run just this stage (repeatable)")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    out = main_stages(args.only, args.quiet)

    print("\n---- summary ----")
    if "content" in out:
        c = out["content"]
        print(f"content   files={c['fileCount']} json={c['jsonCount']} "
              f"loc={c['locCount']} locRecords={c['locRecordTotal']:,} "
              f"failures={c['failureCount']}")
    if "interface" in out:
        i = out["interface"]
        print(f"interface paths={i['pathCount']:,} text={i['textCount']:,} "
              f"binary={i['binaryCount']:,} unreadable={i['unreadableCount']} "
              f"sha256Mismatches={i['sha256MismatchCount']}")
    if "cache" in out:
        k = out["cache"]
        print(f"cache     files={k['fileCount']} records={k['recordTotal']:,} "
              f"tiers={k['tierCounts']}")
    return out


if __name__ == "__main__":
    main()
